Version 1.0.0 - support for SIA, pCloud, CMGR

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,6 +10,14 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+      - name: Check if VERSION file is updated
+        if: startsWith(github.ref_name, 'PR-')
+        run: |
+          git fetch origin master
+          if ! git diff --name-only HEAD origin/master | grep -q '^VERSION$'; then
+            echo "VERSION file was not updated. Failing the build."
+            exit 1
+          fi
       - name: Set up golang 1.24
         uses: actions/setup-go@v4
         with:
@@ -52,7 +60,7 @@ jobs:
         uses: rickstaa/action-create-tag@v1
 #        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
         with:
-          tag: ${{ env.BUILD_TAG }}
+          tag: ${{ env.BUILD_VERSION }}
           tag_exists_error: false
       - name: GoReleaser
 #        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
